[package]
name = "pngme"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pngme"
path = "src/bin/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.2.0"
structopt = "0.3.26"
